parser: '@typescript-eslint/parser'
parserOptions:
  project: './packages/subgraph/tsconfig.json'

# Custom eslint settings for the subgraph can be defined here
ignorePatterns:
  - imported/
  - generated/
  - tests/
  - extended-schema.ts

overrides:
  - files: '*.ts'
    rules:
      # graphProtocol BigInt class is a valid type
      '@typescript-eslint/ban-types': 'off'
