name: 'formatting & linting'

on:
  workflow_dispatch:
  workflow_call:

jobs:
  checks:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 16

      - name: 'Install the dependencies'
        run: 'yarn install'

      - name: 'Check code formatting'
        run: yarn prettier:check

      - name: 'Check code linting'
        run: yarn lint
