name: Documentation Update

on:
  workflow_call:
  push:
    branches:
      - develop
    paths:
      - 'packages/js-client/**'
      - '.github/workflows/js-client-*.yml'

jobs:
  update_docs:
    if: github.actor != 'arabot-1'
    permissions: read-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sdk repo
        uses: actions/checkout@v3
        # with:
        #   token: ${{ secrets.ARABOT_PAT }}
      - name: Install node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          node-version: 16.x
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Generate Client Docs
        run: yarn run docs:client
      - name: Generate TokenVoting Docs
        run: yarn run docs:tokenVoting
      - name: Generate AddresslistVoting Docs
        run: yarn run docs:addresslistVoting
      - name: Generate Multisig Docs
        run: yarn run docs:multisig
      - name: Generate examples Docs
        run: yarn run docs:examples
      - name: Checkout developer-portal repo
        uses: actions/checkout@v3
        with:
          repository: aragon/developer-portal
          ref: staging
          path: developer-portal
          # token: ${{ secrets.ARABOT_PAT }}
      - name: Clean the docs/sdk folder in the developer-portal
        run: rm -rf $GITHUB_WORKSPACE/developer-portal/docs/sdk
      - name: Copy the docs folder to the developer-portal
        run: cp -R ./docs/sdk $GITHUB_WORKSPACE/developer-portal/docs/sdk
      - name: Get short commit hash
        id: hash
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ARABOT_PAT }}
          path: developer-portal
          commit-message: 'Update the Aragon SDK docs by commit ${{ steps.hash.outputs.sha_short }}'
          committer: 'Arabot <arabot-1@users.noreply.github.com>'
          branch: patch/aragon-sdk-docs
          delete-branch: true
          title: Update the Aragon SDK docs
          body: 'Automated update by Github actions (Run: [${{ github.run_id }}](https://github.com/aragon/sdk/actions/runs/${{ github.run_id }}))'
          reviewers: ${{ github.actor }}
          team-reviewers: devrel
