name: 'subgraph'

on:
  workflow_dispatch:
  push:
    paths:
      - 'packages/subgraph/**'
      - 'packages/contracts/**' # Make sure to watch changes in contracts as well
      - '.github/workflows/subgraph-*.yml'

jobs:
  formatting-linting:
    uses: ./.github/workflows/formatting-linting.yml
  tests:
    runs-on: 'ubuntu-latest'
    defaults:
      run:
        working-directory: packages/subgraph
    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 18

      - name: 'Install dependencies for contracts'
        run: yarn install
        working-directory: packages/contracts

      - name: 'Install the dependencies for subgraph'
        run: yarn install

      - name: 'Build the subgraph'
        run: yarn build
        env:
          SUBGRAPH_NETWORK_NAME: ${{ vars.SUBGRAPH_NETWORK_NAME }}
          INFURA_API_KEY: ${{ secrets.INFURA_API_KEY }}

      - name: 'Test the subgraph'
        run: yarn test >> $GITHUB_STEP_SUMMARY
