name: 'subgraph'

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'packages/subgraph/**'
      - 'packages/contracts/**'
      - '.github/workflows/subgraph-*.yml'

jobs:
  formatting-linting:
    uses: ./.github/workflows/formatting-linting.yml
  tests:
    runs-on: 'ubuntu-latest'

    steps:
      - name: 'Check out the repo'
        uses: 'actions/checkout@v3'

      - name: 'Install Node.js'
        uses: 'actions/setup-node@v3'
        with:
          cache: 'yarn'
          node-version: 18

      - name: 'Install root dependencies'
        run: 'yarn install --frozen-lockfile'
        working-directory: .

      - name: 'Install dependencies for contracts'
        run: 'yarn install --frozen-lockfile'
        working-directory: packages/contracts

      - name: 'Install the dependencies for subgraph'
        run: 'yarn install --frozen-lockfile'
        working-directory: packages/subgraph

      - name: 'Build the subgraph'
        run: yarn build
        working-directory: packages/subgraph
        env:
          SUBGRAPH_NETWORK_NAME: ${{ vars.SUBGRAPH_NETWORK_NAME }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}

      - name: 'Test the subgraph'
        run: yarn test
        working-directory: packages/subgraph
