name: 'subgraph Deploy'

on:
    workflow_dispatch:
    push:
        branches:
            - 'main'
        paths:
            - 'packages/contracts/**'
            - 'packages/subgraph/**'
            - '.github/workflows/subgraph-deploy.yml'

jobs:
    formatting-linting:
        uses: ./.github/workflows/formatting-linting.yml
    prepare:
        runs-on: 'ubuntu-latest'
        outputs:
            environment: ${{ steps.prepare.outputs.environment }}
            matrix: ${{ steps.prepare.outputs.matrix }}
        steps:
            - uses: 'actions/checkout@v3'
            - name: Prepare
              id: prepare
              run: python .github/scripts/subgraph-build-matrix.py '${{ github.ref }}'

    deploy:
        runs-on: 'ubuntu-latest'
        needs: ['formatting-linting', 'prepare']
        strategy:
            fail-fast: false
            matrix: ${{ fromJSON(needs.prepare.outputs.matrix) }}
        defaults:
            run:
                working-directory: packages/subgraph
        steps:
            - name: 'Check out the repo'
              uses: 'actions/checkout@v3'

            - name: 'Install Node.js'
              uses: 'actions/setup-node@v3'
              with:
                  cache: 'yarn'
                  node-version: 18

            - name: 'Install the dependencies'
              run: 'yarn install'

            - name: 'Build the subgraph'
              run: 'yarn build'
              env:
                  INFURA_API_KEY: ${{secrets.INFURA_API_KEY}}
                  NETWORK_NAME: 'goerli'

            - name: 'Test the subgraph'
              run: 'yarn test >> $GITHUB_STEP_SUMMARY'

            - name: 'Deploy the subgraph'
              run: 'yarn deploy'
              env:
                  SUBGRAPH_NAME: osx-hardhat-template
                  NETWORK_NAME: ${{ matrix.network }}
                  GRAPH_KEY: ${{ secrets.GRAPH_KEY }}
                  GRAPH_NODE: 'https://app.satsuma.xyz/api/subgraphs/deploy'
